version: '2'

services:
  dynamo-php-hash-phpfpm:
    image: 'bitnami/php-fpm:8.1'
    volumes:
      - ../.:/app
      - ./php/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
    restart: unless-stopped